import pandas as pd

import csv

punctuations = '!?\":,/.;()[]*'
punc_table = str.maketrans({key: None for key in punctuations})

def process_whisper_output(text):
    """
        Process the prediction from whisper model

        Arguments
        ---------
        text: str

        Returns
        -------
        The processed text.
    """
    t = text.replace('\n', '')
    a = t.translate(punc_table)
    b = a.replace('-', ' ').replace("«", " ").replace("»", " ")
    return ''.join(b.lower().strip())


def get_data_from_whisper(directory, model_prefix, corpus_name):
    """
    Read the data generated by whisper.

    Args:
        directory (str): The directory path.
        model_prefix (str): The prefix for the model.
        corpus_name (str): The name of the corpus.

    Returns:
        list: The predictions of the whisper model.
    """
    file_path = f"{directory}{model_prefix}{corpus_name}_out.txt"
    f = open(file_path, 'r')
    preds = [process_whisper_output(row[1]) for row in csv.reader(f, delimiter='\t')]
    f.close()
    return preds


def create_file(sentences, asr_model, model_prefix, corpus_name, folder_to_save):
    f = open(folder_to_save + asr_model + "_" + model_prefix + corpus_name + ".fr", "w")
    for s in sentences:
        f.write(str(s) + "\n")
    f.close()


def get_text_and_generate_file(folder_data_asr, model_prefix, corpus_name, folder_to_save, asr_model):
    src_sentences = get_data_from_whisper(folder_data_asr, model_prefix, corpus_name)
    create_file(src_sentences, asr_model, model_prefix, corpus_name, folder_to_save)


if __name__ == '__main__':
    # get_text_and_generate_file("/gpfswork/rech/czj/uef37or/ASR_S2P_data/whisper-large-v3/", "large-v3_test_",
    #                            "commonvoice",
    #                            "/gpfswork/rech/czj/uef37or/NMT_transformers/exp_commonvoice/commonvoice_process/",
    #                            "whisper")
    get_text_and_generate_file("/gpfswork/rech/czj/uef37or/ASR_S2P_data/seamlessm4t-large-v2/", "large-v2_test_",
                               "commonvoice",
                               "/gpfswork/rech/czj/uef37or/NMT_transformers/exp_commonvoice/commonvoice_process/",
                               "seamless")
